### ISSUE TITLE
Refresh Login Functionality

### ISSUE THREAD

**Issue by andrewcomputsci2019** [andrewcomputsci2019/JStream#2]
Use created tokens and send back to the user using JSON

**Comment by andrewcomputsci2019** [comment]
login function use username password and refresh token

**Comment by mhayescs19** [comment]
- [x] validate refresh token and generate fresh auth and refresh tokens

**Comment by mhayescs19** [comment]
[Refresh Authentication Branch](https://github.com/andrewcomputsci2019/JStream/tree/refreshAuthentication)
